[[redirects]]
  from = "/api/*"
  to = "https://vmi2848672.contaboserver.net/cbt/api/:splat"
  status = 200
  force = true
  headers = {
    Access-Control-Allow-Origin = "*",
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS",
    Access-Control-Allow-Headers = "Content-Type, Authorization"
  }