[[redirects]]
  from = "/api/*"
  to = "https://vmi2848672.contaboserver.net/cbt/api/:splat"
  status = 200
  force = true

  # Use a nested table for headers
  [redirects.headers]
    Access-Control-Allow-Origin = "https://cbtafrica.netlify.app"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-CSRFToken"
    Access-Control-Allow-Credentials = "true"

# Handle preflight requests
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://cbtafrica.netlify.app"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-CSRFToken"
    Access-Control-Allow-Credentials = "true"
    Access-Control-Max-Age = "86400"
